replicaCount: 1
image:
  repository: nginx
  pullPolicy: Always
  tag: latest
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
configmap: nginxConfigMap
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  hosts:
  - host: test.ae25bb730d6043dd9638.northeurope.aksapp.io
    paths:
    - path: /
      backend:
        serviceName: chart-example.local
        servicePort: 3000
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
